### ISSUE TITLE
Board size change

### ISSUE THREAD

**Issue by indikat0r** [maxl95/RGBW-Controller#2]
Hi Maximilian
to use the JLCPCB Assembly Service,
the board should have at least 20x20mm Size but it has 34.77x19.68mm
How can i change the board size to 35x20mm?

Schöne Grüße
Martin

**Comment by maxl95** [comment]
Hallo Martin,
du kannst das Board nach belieben mit dem Programm "Target 3001" bearbeiten. Für private zwecke ist es kostenlos.

> https://www.ibfriedrich.com/de/index.html

Bei weiteren Fragen, meld dich einfach wieder.
Gruß Maximilian

**Comment by maxl95** [comment]
@indikat0r ich habe das ganze Projekt in KiCAD neu gezeichnet und im Zuge dessen die Boardhöhe auf 35mm angepasst, damit man bei JLC ein Panel erstellen kann.
Gruß Maximilian
